@url = http://localhost:3312

### GET PERSONS
GET {{url}}/persons

### GET PERSON
GET {{url}}/persons/gPD6pT

### GET PERSON
GET {{url}}/persons/jwiEs3

### GET NON-EXISTENT PERSON
GET {{url}}/persons/nnnnn

### DELETE PERSON
DELETE {{url}}/persons/gPD6pT

### DELETE NON-EXISTENT PERSON
DELETE {{url}}/persons/nnnnn

### CREATE PERSON
POST {{url}}/persons
content-type: application/json
	
{
	"firstName": "Emily222",
	"lastName": "Christensen",
	"age": 51
}

### UPDATE PERSON
PUT {{url}}/persons
content-type: application/json
	
{
	"id": "Wdc6hO",
	"firstName": "Emily",
	"lastName": "Christensen",
	"age": 51
}